### ISSUE TITLE
You shouldn't be building a newlib toolchain

### ISSUE THREAD

**Issue by palmer-dabbelt** [isrc-cas/PLCT-Toolbox#1]
https://github.com/isrc-cas/PLCT-Toolbox/blob/2f14e89560d0b9ff7f97b2d4e0163a7ee47c1695/build_riscv_toolchain.sh#L14

Just pass "--enable-linux" on the configure command line and do a "make", that will get you the right stuff.  The newlibtoolchain will just confuse people, as it's not strictly the Linux ABI.

**Comment by lazyparser** [comment]
Hi Palmer,

thank you for suggestion. this script was used for multiple purposes, for some guys in PLCT lab would use both the linux version and newlib toolchain.

I guess you found this script from v8-riscv porting project, which indeed don't need it. indeed, for porting developers it might be confused. I'd separate it later.
